// Autogenerated file
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkghlqzhzpvgjequppel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZ2hscXpoenB2Z2plcXVwcGVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTU5MTMsImV4cCI6MjA3MzMzMTkxM30.kuY_cp11D9a2Zu0PujbcweKP-awVtlXg2-cfNbW7EHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});